#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d '1' '2' '3' '4' '5' '6'

xsetroot -cursor_name left_ptr &

# bspwm Config

bspc config window_gap					14
bspc config split_ratio					0.51
bspc config single_monocle				true
bspc config borderless_monocle				false
bspc config gapless_monocle				false

bspc config border_width 2
bspc config top_padding 50
bspc config bottom_padding 2
bspc config left_padding 2
bspc config right_padding 2
bspc config normal_border_color "#32344a"
bspc config active_border_color "#444b6a"
bspc config focused_border_color "#80a8fd"
bspc config presel_feedback_color "#7aa2f7"

bspc config focus_follows_pointer			true
bspc config pointer_follows_focus			false
bspc config pointer_motion_interval			5
bspc config pointer_modifier				mod4
bspc config pointer_action1				move
bspc config pointer_action2				resize_side
bspc config pointer_action3				resize_corner

# Autostart Programs
feh -z --no-fehbg --bg-fill $HOME/Bilder/Hintergründe/stylized-snowy-mountain-landscape-3440x1440-v0-p6p4x7xnd4vb1.png
gentoo-pipewire-launcher &
picom --daemon &
dunst &
$HOME/.config/polybar/launch.sh
stalonetray --window-type normal &
sleep 0.5
xdotool windowunmap "$(xdotool search --class stalonetray)"