#!/bin/bash

fensterklasse="stalonetray"

window_id=$(xdotool search --class $fensterklasse)

window_status=$(xwininfo -id $window_id | grep "Map State" | awk '{print $3}')

if [ "$window_status" == "IsViewable" ]; then
    xdotool windowunmap $window_id
else
    xdotool windowmap $window_id
fi